version: '3'
services:
  node-app:
    container_name: npm1
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - '3001:3000'
    volumes:
      - /app/node_modules
      - .:/app
  node-test:
    container_name: npm-test
    build:
      context: .
      dockerfile: dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: npm run test
